### ISSUE TITLE
Problems with 'm' language

### ISSUE THREAD

**Issue by Slightsubset717** [ligangwang/m#104]
Hi,
The on progress m language is great, **but it could do better**.

Currently, when you have a problem with the code, you can **no longer** rerun the code. There **wouldn't be any results**.

Also, I feel like the version should be **moved somewhere else**.

It would be great if it was fixed.

_Thanks._

**Comment by ligangwang** [comment]
Thanks for the feedback. the error handling will be improved in the future. the version is always displayed in the footer section now. I'm closing this now.
